baseURL = "https://www.karlk.net"
enableRobotsTXT = true
languageCode = "en-us"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]

[params]
math = true
socialIcons = [
  {name = "twitter",       url = "https://twitter.com"},
  {name = "stackoverflow", url = "https://stackoverflow.com"},
  {name = "github",        url = "https://github.com"},
]
